### ISSUE TITLE
WI-Fi

### ISSUE THREAD

**Issue by rhydianbevan** [johnlimlc/HP15DA-0XXX-OPENCORE#1]
I bought the WiFi card you suggested and I set up the itlwm kext the other day it works but it cuts off every so often meaning I have to restart or try and turn the WiFi on and off again the same happens on airportitwlm I'm not sure why. Also it only wants to connect to a 5ghz network doesn't work on any of my 2.4ghz networks Are you facing any issues ? Any help would be much appreciated on solving this issue because I can't really use it when it keeps cutting out.

**Comment by johnlimlc** [comment]
Please refer to my latest release version 1.1 to see if it solves your issues.
I am using as now uploading and writing this message to you with stability.
Hope it will work for you too.
