### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by Overc1ocker** [johnlimlc/HP15DA-0XXX-OPENCORE#2]
Hello! I hackintoshed this exact laptop a few months ago and I am pleased with the performance. However I have a few questions. 
- Where did you get your SSDTs? I spent hours trying to play around with them until I found that the RTC had to be patched out.  
- Does your touchscreen work? If so, how did you fix it?
- Do your brightness keys work? If so, how'd you fix that.
- I also noticed there was a patch for the ambient light sensor. I didn't even know this model had one of those. Does it work well?

**Comment by johnlimlc** [comment]
It was pull from Olarila.
Mine does not have a touchscreen.
Nope, it is not working as well.
Nope, no ambient light sensor.
